name: 'ai_lab'

config-version: 2
version: '0.1'

profile: 'ai_lab'

model-paths: ["models"]
seed-paths: ["data"]  # <-- Added seed path to store CSV files

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ai_lab:
    transformations:
      schema: webshop
      materialized: table

seeds:
  ai_lab:
    webshop:
      +schema: webshop  # <-- Ensures the seed is loaded into the "webshop" schema
      +column_types:
        id: integer
        customerid: integer
        ordertimestamp: timestamp
        shippingaddressid: integer
        total: numeric
        shippingcost: numeric
        created: timestamp
        updated: timestamp
