name: 'ai_lab'

config-version: 2
version: '0.1'

profile: 'ai_lab'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ai_lab:
    transformations:
      schema: webshop
      materialized: table  
