name: 'ai_lab'

config-version: 2
version: '0.1'

profile: 'ai_lab'

model-paths: ["models"]
seed-paths: ["data"]  # Ensures dbt looks for CSV files in the 'data/' directory

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds:
  ai_lab:
    order:
      +schema: webshop_v2  # Now loads into the webshop_v2 schema
      +column_types:
          id: integer
          customerid: integer
          ordertimestamp: timestamp
          shippingaddressid: integer
          total: numeric
          shippingcost: numeric
          created: timestamp
          updated: timestamp
    address:
      +schema: webshop_v2  # Ensures it loads into webshop_v2 schema
      +column_types:
          customerid: integer
          firstname: text
          lastname: text
          address1: text
          address2: text
          city: text
          zip: text  # ZIP codes often contain letters, so use TEXT
          created: timestamp
          updated: timestamp
    article:
      +schema: webshop_v2  # Ensures data loads into webshop_v2 schema
      +column_types:
          id: integer
          productid: integer
          ean: text
          colorid: integer
          size: integer
          description: text
          originalprice: numeric
          reducedprice: numeric
          taxrate: integer
          discountinpercent: integer
          currentlyactive: boolean  # Assuming "t" and "f" represent true/false
          created: timestamp
          updated: timestamp
    customer:
      +schema: webshop_v2
      +column_types:
          id: integer
          firstname: text
          lastname: text
          gender: text
          email: text
          dateofbirth: text  # Can be converted to DATE in a dbt model later
          currentaddressid: integer
          created: timestamp
          updated: timestamp
    labels:
      +schema: webshop_v2
      +column_types:
          id: integer
          name: text
          slugname: text
          icon: text
    order_positions:
      +schema: webshop_v2
      +column_types:
          id: integer
          orderid: integer
          articleid: integer
          amount: integer
          price: numeric  # Ensure "$" is removed before ingestion
          created: timestamp
          updated: timestamp
    products:
      +schema: webshop_v2
      +column_types:
          id: integer
          name: text
          labelid: integer
          category: text
          gender: text
          currentlyactive: boolean  # Assuming "t" and "f" represent true/false
          created: timestamp
          updated: timestamp 
    stocks:
      +schema: webshop_v2
      +column_types:
          id: integer
          articleid: integer
          count: integer
          created: timestamp
          updated: timestamp 
