name: 'ai_lab'

config-version: 2
version: '0.1'

profile: 'ai_lab'

model-paths: ["models"]
seed-paths: ["data"]  # Uncomment if using dbt seed
macro-paths: ["macros"]  # Macros directory for SQL execution
script-paths: ["scripts"]  # Directory for raw SQL files

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ai_lab:
    load:
      schema: webshop
      materialized: table
      pre-hook: "{{ load_sql_dump('scripts/order.sql') }}"  # Runs order.sql before dbt models
