ai_lab:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ conn.postgres_conn.login }}"
      password: "{{ conn.postgres_conn.password }}"
      port: 5432
      dbname: webshop_v2
      schema: webshop  # This ensures that all dbt objects go into webshop_v2
      threads: 6

#working version
